<<<<<<< HEAD
language: python

python:
  - "2.7"

cache: pip
=======
sudo: false
language: python

python:
  - "2.7_with_system_site_packages"
>>>>>>> 4c105b0b6ce49df64cd2fe193f96e9b7c16870b5

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
<<<<<<< HEAD
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true
=======

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

>>>>>>> 4c105b0b6ce49df64cd2fe193f96e9b7c16870b5

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
<<<<<<< HEAD
  - pip install reportlab
  - pip install unidecode
  - pip install http://xmlsoft.org/sources/python/libxml2-python-2.6.21.tar.gz
  - pip install https://github.com/odoo-brazil/pyxmlsec/archive/master.zip
  - pip install https://github.com/odoo-brazil/geraldo/archive/master.zip
  - pip install https://github.com/odoo-brazil/PySPED/archive/8.0.zip --allow-external PyXMLSec --allow-insecure PyXMLSec
  - travis_install_nightly

before_script:
  - chmod +x configure_locale.sh

script:
  - ./configure_locale.sh
=======
  - pip install unidecode
  - pip install python-ldap
  - pip install suds
  - travis_install_nightly

script:
>>>>>>> 4c105b0b6ce49df64cd2fe193f96e9b7c16870b5
  - travis_run_tests

after_success:
  coveralls
